export const initialData = () => {
    let d = {};
    for(let i=0; i<100; i++){ d[i.toString().padStart(2,"0")] = 0; }
    return d;
  };
  
  export const defaultRules = "r=+,အာ,ပတ်လည်,ပြန်,အပြန်\npo=ပါဝါ,ပါဝ,ပဝါ,power,pw\nnk=နက္ခတ်,နတ်က္ခတ်,နက္ခ,နက,နကတ\neq=အပူး,ပူး,တူ,ညီ\npeq=စုံပူး\nneq=မပူး\nb=ဘရိတ်,ဘရိတ်,ဘရိတ်,ဘရိတ်,breik,break,br\nkwp=ခွေပူး,ခပ\nkw=ခွေ,ခွေ,ခွေ,ခွေ,kwe,khwe\npp=စုံစုံ,စစ,ss\npn=စုံမ,စမ,sm\nnp=မစုံ,မစ,ms\nnn=မမ,mm\np.=စုံထိပ်,စထိပ်,sd\nn.=မထိပ်,မထိပ်,md\n.p=စုံပိတ်,စပိတ်,sp\n.n=မပိတ်,မပိတ်,mp\nbro=ညီအစ်ကို,ညီကို,ညီအကို,ညက,ညအက\n1b=1ဘရိတ်,၁ဘရိတ်\nbig=အကြီး,ကြီး\nsmall=အသေး,သေး";
  
  export const dict = {
    mm: {
      manual_entry: "ရိုးရိုးသွင်းမည်",
      bulk_entry: "အများကြီးသွင်းမည်",
      expire_date: "ကုန်ဆုံးရက်",
      match_win: "ပေါက်ဂဏန်း တိုက်မည်",
      ledger_summary: "စာရင်းချုပ် (Ledger)",
      quick_settings: "အမြန်ပြင်ဆင်မှု (Settings)",
      device_list: "Logged in Device စာရင်း",
      net_risk: "လုပ်ငန်းတစ်ခုလုံး လက်ကျန်ငွေ",
      morning: "မနက်ပိုင်း",
      evening: "ညနေပိုင်း",
      end_session: "ပွဲသိမ်း",
      over_limit: "Over Limit:",
      entry_2d: "2D စာရင်းသွင်း",
      back: "အနောက်သို့",
      quick_entry: "ဂဏန်းများ/စာကြောင်းများ ထည့်ရန်",
      paste_btn: "📋 Paste ချမည်",
      paste_ph: "စာကြောင်းများစွာ Paste ချပါ... (ဥပမာ: 12 34 500)",
      submit_all: "အားလုံးကို စာရင်းသွင်းမည်",
      agent: "ထိုးသား/ကော်စား (Agent)",
      master: "အပေါ်ဒိုင် (Master)",
      action: "လုပ်ဆောင်ချက်",
      in_receive: "IN (ယူ)",
      out_send: "OUT (တင်)",
      num_ph: "ဂဏန်းများ (po, 12...)",
      price_ph: "စျေးနှုန်း",
      add_record: "ADD (စာရင်းသွင်းမည်)",
      sub_record: "SUBTRACT (ဒိုင်တင်မည်)",
      undo_last: "နောက်ဆုံးသွင်းခဲ့သောစာရင်း ပြန်ဖျက်မည်",
      count: "အရေအတွက်:",
      items: "ကွက်",
      total: "စုစုပေါင်း:",
      num_grid: "နံပါတ်အကွက်များ",
      hot_ph: "🔥 Hot ဂဏန်းများထည့်ရန် (ဥပမာ: 12, 34)",
      top_risk: "Top Risk:",
      history_title: "ဖြတ်ပိုင်းမှတ်တမ်းများ",
      clear_all: "ရှင်းလင်းမည်",
      all_agents: "စာရင်းရှင် အားလုံး",
      no_history: "မှတ်တမ်းမရှိသေးပါ။",
      all: "အားလုံး",
      agent_tab: "ထိုးသား",
      master_tab: "ဒိုင်",
      settle_win: "ထွက်ဂဏန်းဖြင့် စာရင်းရှင်းမည်:",
      win_ph: "ဂဏန်း",
      add_new: "အသစ်ထည့်မည်",
      no_ledger: "စာရင်း မရှိသေးပါ။",
      details: "အသေးစိတ်",
      edit: "ပြင်မည်",
      total_in: "စုစုပေါင်း တင်ငွေ (IN)",
      total_out: "ဒိုင်တင်ငွေ (OUT)",
      comm_get: "ရမည့် ကော်မရှင်",
      comm_pay: "ပေးရမည့် ကော်မရှင်",
      net_bal: "လက်ထဲကျန်ငွေ",
      net_bal_pay: "ပေးရန်ကျန်ငွေ",
      loss: "(ရှုံး)",
      payout_mult: "2D လျော်ကြေး (ဆ)",
      total_payout: "စုစုပေါင်း လျော်ရမည့်ငွေ",
      admin_net_profit: "စုစုပေါင်း မြတ်ငွေ",
      admin_net_loss: "စုစုပေါင်း လျော်ရမည့်ငွေ",
      admin_break_even: "စုစုပေါင်း အရှုံးအမြတ်မရှိ",
      users_matched: "ဤဂဏန်းအား စာရင်းသွင်းထားသူ",
      users_count: "ဦးရှိပါသည်။",
      no_winner: "ဤဂဏန်းအား ထိုးထားသူ/ဒိုင်တင်ထားသူ မရှိပါ။",
      data_reset: "ဒေတာစီမံခန့်ခွဲမှု (Data Reset)",
      reset_desc: "နောက်ပွဲစဉ်/နောက်ရက် အတွက် စာရင်းများကို ရှင်းလင်းပြီး သုညကနေ ပြန်စပါမည်။ (ကိုယ်စားလှယ် အမည်စာရင်းများ မပျက်ပါ)",
      reset_btn: "လက်ရှိပွဲစဉ်ကို သိမ်းမည်",
      set_2d: "2D Setting",
      set_3d: "3D Setting",
      set_mm85: "MM85 Setting",
      payout_rate: "လျော်ကြေး ရာခိုင်နှုန်း:",
      split_rate: "ခွဲ ရာခိုင်နှုန်း:",
      twut_rate: "တွတ် ရာခိုင်နှုန်း:",
      global_limit: "အများဆုံး လစ်မစ် (Limit):",
      gen_set: "General Setting",
      use_comma: "2D မှတ်တမ်း Comma ယူမယ်",
      comma_desc: "မှတ်ချက် - နံပါတ်ကြားတွင် Comma (,) မယူပါ",
      split_r: "R ထိုးကြေးကို တစ်ဝက်စီယူမယ်",
      equal_price: "'=' နောက်က ဂဏန်းကို ထိုးကြေးအဖြစ်ယူမယ်",
      quick_prices_label: "အမြန်ရွေးချယ်ရန် စျေးနှုန်းများ",
      quick_prices_desc: "ကော်မာ (,) ခြားပြီး စျေးနှုန်းများသတ်မှတ်ပါ။",
      custom_shortcuts: "အတိုကောက် စာလုံးများ",
      shortcuts_desc: "မိမိစိတ်ကြိုက် အတိုကောက်စာလုံးများကို သတ်မှတ်ပါ။ (ဥပမာ: r=ပြန်)",
      danger_zone: "အန္တရာယ်ဇုန် (Danger Zone)",
      danger_desc: "App တစ်ခုလုံးကို အစကနေပြန်စလိုမှသာ အောက်ပါခလုတ်ကို နှိပ်ပါ။",
      del_all: "ဒေတာအားလုံးကို အပြီးတိုင်ဖျက်မည်",
      risk_limits: "စောင့်ကြည့်ဂဏန်းများ",
      hi_lo: "များ ➔ နည်း",
      lo_hi: "နည်း ➔ များ",
      over_lim_tab: "လစ်မစ်ကျော်",
      above_80: "80% အထက်",
      number: "ဂဏန်း",
      progress: "အခြေအနေ",
      amount: "ပမာဏ",
      nav_home: "ပင်မ",
      nav_entry: "စာရင်းသွင်း",
      nav_grid: "အကွက်",
      nav_monitor: "စောင့်ကြည့်",
      nav_ledger: "စာရင်း",
      nav_history: "မှတ်တမ်း",
      edit_agent: "စာရင်းရှင် ပြင်ဆင်မည်",
      add_agent: "စာရင်းရှင် အသစ်ထည့်မည်",
      name: "အမည်",
      comm_percent: "ကော်မရှင် %",
      limit: "လစ်မစ် (Limit)",
      delete: "ဖျက်မည်",
      update_btn: "Update ပြင်ဆင်မည်",
      add_new_btn: "အသစ်ထည့်မည်",
      help_title: "အသုံးပြုနည်း လမ်းညွှန်",
      got_it: "နားလည်ပါပြီ",
      pay_to_master: "ဒိုင်ကို ပေးရန်ရှိငွေ",
      win_from_master: "ဒိုင်မှ ရမည့် ပေါက်ငွေ",
      agent_win: "ထိုးသား ပေါက်ငွေ",
      admin_receive: "ကိုယ်က ရမည် (Receive)",
      admin_pay: "ကိုယ်က ပေးရမည် (Pay)",
      no_nums_agent: "ဤစာရင်းရှင်အတွက် ဂဏန်းများမရှိသေးပါ။",
      close: "ပိတ်မည်",
      alert: "အသိပေးချက်",
      confirm: "အတည်ပြုရန်",
      cancel: "မလုပ်ပါ",
      ok: "အိုကေ",
      success: "အောင်မြင်ပါသည်",
      warning: "သတိပြုရန်",
      enter_agent_name: "စာရင်းရှင် အမည် ထည့်သွင်းပေးပါ။",
      agent_added: "အား စာရင်းသွင်းပြီးပါပြီ။",
      del_confirm: "ဖျက်ပစ်မှာ သေချာပါသလား?",
      enter_valid: "စျေးနှုန်း (Price) ထည့်ရန်မေ့နေပါသလား? သို့မဟုတ် ဖော်မတ်မှားနေပါသည်။",
      clip_denied: "Clipboard ယူခွင့်မပြုထားပါ။ ဤ Box ထဲတွင် ဖိပြီး Paste ချပါ ခင်ဗျာ။",
      del_all_conf: "ဒေတာအားလုံးကို ဖျက်ပစ်မှာ သေချာပါသလား?",
      reset_sess_conf: "လက်ရှိ ပွဲစဉ်အတွက် စာရင်းများကို ရှင်းလင်းမည်မှာ သေချာပါသလား?",
      session_cleared: "ပွဲစဉ်သစ်အတွက် စာရင်းများ ရှင်းလင်းပြီးပါပြီ။",
      net_cash_in_hand: "လုပ်ငန်းတစ်ခုလုံး လက်ကျန်ငွေ",
      total_in_net: "စုစုပေါင်း ရငွေ (IN):",
      total_out_net: "စုစုပေါင်း ဒိုင်တင် (OUT):",
      payout_to_players: "ထိုးသားများအား လျော်ငွေ:",
      receive_from_master: "အပေါ်ဒိုင်မှ ရမည့်လျော်ငွေ:",
      bulk_out_title: "📤 လစ်မစ်ကျော်များ ဒိုင်တင်မည်",
      no_master_yet: "Master မရှိသေးပါ",
      preview: "အစမ်းကြည့်ရန် (Preview)",
      quick_out: "အမြန် ဒိုင်တင်မည်",
      delete_history_confirm: "ဒီမှတ်တမ်းကို ဖျက်ပြီး စာရင်းပြန်နှုတ်မှာ သေချာပါသလား?",
      history_deleted: "မှတ်တမ်းဖျက်သိမ်းပြီး စာရင်းပြင်ဆင်ပြီးပါပြီ။",
      edit_history_title: "စျေးနှုန်း (Price) ပြင်ဆင်မည်",
      edit_history_desc: "ဒီမှတ်တမ်းအတွက် စျေးနှုန်းအသစ်ကို ထည့်သွင်းပါ။",
      reset_excess: "မူလကျော်ငွေ",
      export_pdf: "စာရင်းထုတ်မည် (PDF)"
    },
    en: {
      manual_entry: "Manual Entry",
      bulk_entry: "Bulk Paste",
      expire_date: "Expires",
      match_win: "Match Win Number",
      ledger_summary: "Ledger Summary",
      quick_settings: "Quick Settings",
      device_list: "Logged in Devices",
      net_risk: "Total Net Balance",
      morning: "Morning",
      evening: "Evening",
      end_session: "End Session",
      over_limit: "Over Limit:",
      entry_2d: "2D Entry",
      back: "Back",
      quick_entry: "Numbers / Lines Entry",
      paste_btn: "📋 Paste",
      paste_ph: "Type numbers (e.g. po 500)...",
      submit_all: "Submit All Entries",
      agent: "Agent (Player)",
      master: "Master (Up-line)",
      action: "Action Type",
      in_receive: "IN (Receive)",
      out_send: "OUT (Send)",
      num_ph: "Numbers (po, 12...)",
      price_ph: "Price",
      add_record: "ADD (Record In)",
      sub_record: "SUBTRACT (Send Out)",
      undo_last: "Undo Last Entry",
      count: "Count:",
      items: "items",
      total: "Total:",
      num_grid: "Number Grid",
      hot_ph: "🔥 Add Hot Numbers (e.g. 12, 34)",
      top_risk: "Top Risk:",
      history_title: "Receipt History",
      clear_all: "Clear All",
      all_agents: "All Agents",
      no_history: "No history found.",
      all: "All",
      agent_tab: "Agents",
      master_tab: "Masters",
      settle_win: "Settle with Win Number:",
      win_ph: "Number",
      add_new: "Add New",
      no_ledger: "No ledger records.",
      details: "Details",
      edit: "Edit",
      total_in: "Total Received (IN)",
      total_out: "Total Sent (OUT)",
      comm_get: "Comm to Receive",
      comm_pay: "Comm to Pay",
      net_bal: "Net Balance",
      net_bal_pay: "Net Balance (To Pay)",
      loss: "(Loss)",
      payout_mult: "2D Payout (Multiplier)",
      total_payout: "Total Payout",
      admin_net_profit: "Total Net Profit",
      admin_net_loss: "Total Net Loss (To Pay)",
      admin_break_even: "Break Even",
      users_matched: "Users matched:",
      users_count: "users.",
      no_winner: "No winners for this number.",
      data_reset: "Data Management (Reset)",
      reset_desc: "Clear records and restart from zero.",
      reset_btn: "Reset Session Data",
      set_2d: "2D Settings",
      set_3d: "3D Settings",
      set_mm85: "MM85 Settings",
      payout_rate: "Payout Rate:",
      split_rate: "Split Rate:",
      twut_rate: "Twut Rate:",
      global_limit: "Global Limit:",
      gen_set: "General Settings",
      use_comma: "Use Comma in 2D entries",
      comma_desc: "Note - commas are ignored.",
      split_r: "Split bet amount for 'R'",
      equal_price: "Use number after '=' as bet",
      quick_prices_label: "Quick Prices",
      quick_prices_desc: "Set prices separated by commas.",
      custom_shortcuts: "Custom Shortcuts",
      shortcuts_desc: "Define custom shortcuts (e.g. r=rev).",
      danger_zone: "Danger Zone",
      danger_desc: "Factory reset entire app.",
      del_all: "Delete All Data",
      risk_limits: "Risk Limits Monitor",
      hi_lo: "High ➔ Low",
      lo_hi: "Low ➔ High",
      over_lim_tab: "Over Limit",
      above_80: "Above 80%",
      number: "Number",
      progress: "Progress",
      amount: "Amount",
      nav_home: "Home",
      nav_entry: "Entry",
      nav_grid: "Grid",
      nav_monitor: "Monitor",
      nav_ledger: "Ledger",
      nav_history: "History",
      edit_agent: "Edit Agent/Master",
      add_agent: "Add New Agent/Master",
      name: "Name",
      comm_percent: "Commission %",
      limit: "Limit",
      delete: "Delete",
      update_btn: "Update",
      add_new_btn: "Add New",
      help_title: "How to use",
      got_it: "Got it",
      pay_to_master: "Amount to Pay Master",
      win_from_master: "Win Amount from Master",
      agent_win: "Agent Win Amount",
      admin_receive: "Admin Receives",
      admin_pay: "Admin Pays",
      no_nums_agent: "No numbers recorded.",
      close: "Close",
      alert: "Alert",
      confirm: "Confirm",
      cancel: "Cancel",
      ok: "OK",
      success: "Success",
      warning: "Warning",
      enter_agent_name: "Please enter a valid name.",
      agent_added: "saved successfully.",
      del_confirm: "Are you sure to delete?",
      enter_valid: "Invalid format or missing price.",
      clip_denied: "Clipboard access denied. Long press to paste.",
      del_all_conf: "Are you sure you want to delete ALL data?",
      reset_sess_conf: "Reset current session data?",
      session_cleared: "Session cleared successfully.",
      net_cash_in_hand: "Total Net Cash in Hand",
      total_in_net: "Total IN:",
      total_out_net: "Total OUT:",
      payout_to_players: "Payout to Players:",
      receive_from_master: "Receive from Master:",
      bulk_out_title: "📤 Bulk OUT",
      no_master_yet: "No Master Yet",
      preview: "Preview",
      quick_out: "Quick OUT",
      delete_history_confirm: "Are you sure you want to delete this record and revert the balance?",
      history_deleted: "Record deleted and balance reverted successfully.",
      edit_history_title: "Edit Price",
      edit_history_desc: "Enter the new price for this record.",
      reset_excess: "Reset Excess",
      export_pdf: "Export (PDF)"
    }
  };